version: "3"

networks:
  web:
    external: true
  internal:
    external: false
    
services:

  services:
    portfolio:
      image: cedricmarinot/docker-portfolio
      labels:
        - traefik.http.routers.portfolio.rule=Host(`blog.cedricmarinot.fr`)
        - traefik.http.routers.portfolio.tls=true
        - traefik.http.routers.portfolio.tls.certresolver=lets-encrypt
        - traefik.port=80
      networks:
        - internal
        - web

  reverse-proxy:
    image: traefik:v2.6
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
